### PR TITLE
Feature setup

### PR DESCRIPTION
**Pull request by amexabee**
- Set up linters
- Add devise for authentication
- Add rack-cors to communicate with frontend

### CODE REVIEW

**Review by tamana-Balkhi — CHANGES_REQUESTED** [review]
### hello @amexabee 

 ### you did great job but there is some issues you have to work on

# request change 

while starting server I have faced this error please fix it 
error

**Comment by amexabee** [comment]
Thanks for the review @tamana-Balkhi. I will fix it.

**Comment by amexabee** [comment]
Please you can check it now, thanks.

**Review by tamana-Balkhi — APPROVED** [review]
# Hi @amexabee 👋
# STATUS: Approved 🎉
Great work on making the changes requested by a previous review 🥇
Your project is complete! There is nothing else to say other than... it's time to merge it
Congratulations! 🎉 🎉 🎉



To Highlight 🥇
Your Pull Request has a proper title and description. ✔️
Devise has been installed and setup correctly. ✔️
The application allows for registering a new user.✔️
The application asks for confirmation of email. ✔️
A user can reset the password in the application. ✔️
The views in devise for the registration and login have been modified by the student to match the wireframe. ✔️
Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @tamana-Balkhi  ) in your question so I can receive the notification.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
